services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: &minio-end-user ROOTUSER
      MINIO_ROOT_PASSWORD: &minio-end-password CHANGEME123
    command: "server /data --console-address ':9001'"
    volumes:
      - airbend-minio-dev:/data
    ports:
      - 9000:9000
      - 9001:9001

  databend:
    image: datafuselabs/databend
    depends_on:
      - minio
    ports:
      - 8000:8000
    environment:
      QUERY_DEFAULT_USER: databend
      QUERY_DEFAULT_PASSWORD: databend
      QUERY_STORAGE_TYPE: s3
      AWS_S3_ENDPOINT: http://minio:9000
      AWS_S3_BUCKET: databend
      AWS_ACCESS_KEY_ID: *minio-end-user
      AWS_SECRET_ACCESS_KEY: *minio-end-password
    volumes:
      - meta-storage-dir:/var/lib/databend/meta

# docker run -d \
#     --name databend \
#     --net=host \
#     -v meta_storage_dir:/var/lib/databend/meta \
#     -v log_dir:/var/log/databend \
#     -e QUERY_DEFAULT_USER=databend \
#     -e QUERY_DEFAULT_PASSWORD=databend \
#     -e QUERY_STORAGE_TYPE=s3 \
#     -e AWS_S3_ENDPOINT=http://172.31.15.63:9000 \
#     -e AWS_S3_BUCKET=databend \
#     -e AWS_ACCESS_KEY_ID=ROOTUSER \
#     -e AWS_SECRET_ACCESS_KEY=CHANGEME123 \
#     datafuselabs/databend
volumes:
  airbend-minio-dev:
  meta-storage-dir:
