services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: &minio-end-user ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: &minio-end-password ${MINIO_ROOT_PASSWORD}
    command: "server /data --console-address ':9001'"
    volumes:
      - airbend-minio-dev:/data
    ports:
      - 9000:9000
      - 9001:9001

  databend:
    image: datafuselabs/databend
    depends_on:
      - minio
    ports:
      - 8000:8000
    environment:
      QUERY_DEFAULT_USER: ${DATABEND_USER}
      QUERY_DEFAULT_PASSWORD: ${DATABEND_PASSWORD}
      QUERY_STORAGE_TYPE: s3
      AWS_S3_ENDPOINT: http://minio:9000
      AWS_S3_BUCKET: databend
      AWS_ACCESS_KEY_ID: *minio-end-user
      AWS_SECRET_ACCESS_KEY: *minio-end-password
    volumes:
      - meta-storage-dir:/var/lib/databend/meta

volumes:
  airbend-minio-dev:
  meta-storage-dir:
