version: 2

models:
  - name: avg_lat_lon
    description: "Random model"
    columns:
      - name: av_lat
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

      - name: av_lon
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
